#!/bin/bash

rm -f _includes/*

utility_file='mcmc_analysis_tools_rstan.R'
N=$(wc -l $utility_file | sed 's,[ ]*\([0-9]*\) .*$,\1,')

function_names=('extract_expectand_vals' 'extract_hmc_diagnostics'
                'check_all_hmc_diagnostics' 'plot_inv_metric'
                'display_stepsizes' 'plot_num_leapfrogs' 'plot_num_leapfrogs_by_chain'
                'display_ave_accept_proxy' 'apply_transform' 'plot_div_pairs'
                'compute_xi_hat' 'compute_tail_xi_hats' 'check_tail_xi_hats'
                'welford_summary' 'check_variances'
                'split_chain' 'compute_split_rhat' 'compute_split_rhats' 'check_rhat'
                'compute_tau_hat' 'check_tau_hat' 'compute_min_ess_hats' 'check_ess_hat'
                'check_all_expectand_diagnostics' 'summarize_expectand_diagnostics'
                'filter_expectands' 'compute_rhos' 'plot_empirical_correlogram'
                'plot_pairs_by_chain' 'pushforward_chains'
                'mcmc_est' 'ensemble_mcmc_est' 'ensemble_mcmc_quantile_est'
                'plot_expectand_pushforward')
 
for name in ${function_names[@]}; do
  echo $name
  
  # Find start of function
  function_start=$(grep -nh -m1 "$name <- function(" $utility_file | sed 's,\(^[0-9]*\):.*,\1,')
  
  # Find beginning of comments
  comment_start=$(head -$function_start $utility_file | grep -nh ^$ | tail -1 | sed 's,\(^[0-9]*\):.*,\1,')
  let comment_start++

  # Find end of function
  let M=$N-$function_start
  let M++
  
  delta=$(tail -$M $utility_file | grep -nh '^}$' | sed 's,\(^[0-9]*\):.*,\1,')
  
  let function_end=$function_start+$delta
  let function_end=$function_end-1
  
  touch _includes/${name}.qmd
  
  echo "\`\`\`{.python include=\"${utility_file}\" start-line=$comment_start end-line=$function_end}" >> _includes/${name}.qmd
  echo "\`\`\`" >> _includes/${name}.qmd
done
